title: Malachi Massey for Student Body President
description: Malachi Massey is a Computer Science student at the University of Arkansas. He is running for Student Body President to make a difference in the lives of students.
social_media_share_image:
disqus-identifier:
google-analytics:
show-vote: false